#.toml
# categories = ["ğŸ“° essay", "â› tips", "ğŸ—œ tricks", "ğŸ““ report"]
#.yaml
# categories: {}

categories:
  essay:
    id: essay
    icon: "ğŸ“°"
    label: "ğŸ“° essay"
  guide:
    id: guide
    icon: "ğŸ—º"
    label: "ğŸ—º guide"
  tips:
    id: tips
    icon: "â›"
    label: "â› tips"
  tricks:
    id: tricks
    icon: "ğŸ—œ"
    label: "ğŸ—œ tricks"
  report:
    id: report
    icon: "ğŸ““"
    label: "ğŸ““ report"
  naming:
    id: naming
    icon: ""
    label: ""
