functions:
  view:
    id: view
    icon: "ğŸ‘"
    label: "ğŸ‘ view"
  format:
    id: format
    icon: "ğŸ•"
    label: "ğŸ• format"
  modify:
    id: modify
    icon: "ğŸ”§"
    label: "ğŸ”§ modify"
#functions:
#  id:
#  - label: "ğŸ‘ view"
#    name: view
#  - label: "ğŸ• format"
#    name: "format"
#  - label: "ğŸ”§ modify"
#    name: "modify"
#shortcuts:
#  - shortcut: "âŒ˜ -"
#    output: "zoom-out"
#  - shortcut: "âŒ˜ ="
#   output: "zoom-in"

#functions:
#  - ğŸ‘ view
#  - ğŸ• format
#  - ğŸ”§ modify
