guides:
  beginners:
    id: beginners
    icon: "ğŸ¥"
    label: "ğŸ¥ beginner's"
  intermediate:
    id: intermediate
    icon: "ğŸ“"
    label: "ğŸ“ intermediate"
  advanced:
    id: advanced
    icon: "ğŸ”"
    label: "ğŸ” advanced"
