[[journies]]
name = "solo"
icon = "ğŸ£"

[[journies]]
name = "story"
icon = "ğŸ°"

[[journies]]
name = "series"
icon = "ğŸ"

[[journies]]
name = "evergreen"
icon = "ğŸŒ²"


#[[journies]]
#name = "solo"
#icon = "ğŸ£"
#name = "story"
#icon = "ğŸ°"
#name = "series"
#icon = "ğŸ"
#name = "evergreen"
#icon = "ğŸŒ²"

#[journey]
#name = "solo"
#icon = "ğŸ£"
