journies:
  solo:
    id: solo
    icon: "ğŸ£"
    label: "ğŸ£ solo"
  story:
    id: story
    icon: "ğŸ°"
    label: "ğŸ° story"
  story:
    id: series
    icon: "ğŸ"
    label: "ğŸ series"
  evergreen:
    id: evergreen
    icon: "ğŸŒ²"
    label: "ğŸŒ² evergreen"


    #journies:
    # solo:
    #  id: solo
    #   icon: ğŸ£
    #   label: "ğŸ£ solo"
    # - id: story
    #   icon: ğŸ°
    #   label: "ğŸ° story"
    # - id: series
    # icon: ğŸ
    #  label: "ğŸ series"
    #- id: evergreen
    #icon: ğŸŒ²
    #label: "ğŸŒ² evergreen"
