scopes:
  global:
    id: global
    icon: "ğŸŒ"
    label: "ğŸŒ global"
    desc: "program-wide"
    color: "lightblue"
  space:
    id: space
    icon: "ğŸŒŒ"
    label: "ğŸŒŒ space"
    desc: "place where all objects live"
    color: "blue"
  set:
    id: set
    icon: "ğŸ“Š"
    label: "ğŸ“Š set"
    desc: "within set view"
    color: "green"
  beyond:
    id: beyond
    icon: "ğŸ"
    label: "ğŸ beyond program"
    desc: "applies beyond scope of program"
    color:
  object:
    id: object
    icon: "âš›ï¸"
    label: "âš›ï¸ object"
    desc: "object-card view"
    color: "purple"
  menu-bar:
    id: menu-bar
    icon: "â–­"
    label: "â–­ menu-bar"
    desc: "top-most apple menu-bar"
    color: "gray"
