tags:
  origin:
    id: origin
    icon: "ğŸ—¿"
    label: "ğŸ—¿ origin"
    desc: "origination of"
  essay:
    id: essay
    icon: "ğŸ“°"
    label: "ğŸ“° essay"
    desc: "my writings/perspective on"
  review:
    id: review
    icon: "â­ï¸"
    label: "â­ï¸ review"
    desc: "my review/analysis of a thing"
  report:
    id: report
    icon: "ğŸ““"
    label: "ğŸ““ report"
    desc: "reporting on"
  shortcut:
    id: shortcut
    icon: "ğŸ¯"
    label: "ğŸ¯ shortcut"
    desc: "shortcuts to get you there faster"
  all-ways:
    id: all-ways
    icon: "ğŸ’ "
    label: "ğŸ’  all-ways"
    desc: "all-ways to do one thing"
  how-to:
    id: how-to
    icon: "â”"
    label: "â” how-to"
    desc: "how-to guide"
